language: node_js

node_js:
- "stable"
- "12.0"
- "10.0"

matrix:
    fast_finish: true
    include:
        - node_js: stable
          env: COMMAND=test:cov

    allow_failures:
        - node_js: '10.0'

sudo: false

cache:
    directories:
        - node_modules

env:
  - COMMAND=test

script: 
  - npm run ${COMMAND:-"test"}

after_script:
  - npx codecov
